name: Build and Deploy

on:
  push:
    branches: ["main"]

env:
  ENVS: "envs"

# for AWS credentials and k8s setting
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      # checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CONNECT_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: login to AWS ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-to-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_FILE_NAME: ${{ vars.DOCKERFILE }}
          ARGS_ACTIVE_PROFILE: ${{ vars.PROFILE }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest --build-arg ACTIVE_PROFILES=$ARGS_ACTIVE_PROFILE . 
          docker push $REGISTRY/$REPOSITORY --all-tags

      - name: install kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.K8S_VERSION }} # default is latest stable

      - name: set k8s context
        id: set-k8s-context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
          context: #If left unspecified, current-context from kubeconfig is used as default

      - name: refresh deployment
        id: refresh-k8s-deployment
        run: |
          kubectl rollout restart deployment ${{ vars.K8S_DEPLOYMENT_NAME }} -n ${{ vars.K8S_NAMESPACE }}
